FROM nginx

COPY build /usr/share/nginx/html



############## fetch stage ##############

############## packages stage ##############

############## build stage ##############

############## runtine stage ##############